Deploy with cdn
wavemaker/docs pull request #373
Opened 2020-11-27 13:25 UTC by RamanaChowdam

2020-11-27 14:46 UTC, krishnaraochintu commented
Looks Good

2020-12-01 06:20 UTC, krishnaraochintu commented
Venu, please review now

2020-12-04 03:37 UTC, jvenugopal approved these changes

2020-12-04 05:14 UTC, prasanth-reddy-wavemaker-com requested changes
There are lots of errors. This cannot be merged in the current state. 

Please use grammarly extension in Visual studio code https://marketplace.visualstudio.com/items?itemName=znck.grammarly

There is also duplication of content in lots of pages. Instead of copy pasting common sections of documentation they should be linked.

2020-12-04 05:14 UTC, prasanth-reddy-wavemaker-com commented on learn/app-development/deployment/app-integration-with-aws-cdn.md
> +- The above command will generate a new folder called **target** in the project sources & generates `project.war` file and `ui-artifacts.zip` file in it. The `ui-artifacts.zip` file have static files
Replace the line with this:

The above command generates two deployable artifacts: `ui-artifacts.zip`, `project.war`. Both these files can be found in `target` folder.

Also replace this sentence:

Use the following commands for unzip and upload to S3.
with
Use the following commands to unzip and upload to S3.

Note that the correct proposition to use here is "to" not "for"

2020-12-04 05:14 UTC, prasanth-reddy-wavemaker-com commented on learn/app-development/deployment/app-integration-with-aws-cdn.md
> +- For unzip the file to a specific folder
Wrong. Replace with:

To unzip the file and store contents in a specific folder

2020-12-04 05:14 UTC, prasanth-reddy-wavemaker-com commented on learn/app-development/deployment/app-integration-with-aws-cdn.md
> +- For upload files to AWS S3 bucket
Upload files to AWS S3 bucket

2020-12-04 05:14 UTC, prasanth-reddy-wavemaker-com commented on learn/app-development/deployment/app-integration-with-azure-cdn.md
> +## WaveMaker App Build Process for CDN support
Please don't repeat this content here. Just link to it.

2020-12-04 05:14 UTC, prasanth-reddy-wavemaker-com commented on learn/app-development/deployment/building-with-maven.md
> +- WaveMaker app is consists of frontend artifacts (HTML, CSS, JS, images, etc), and backend artifacts (Java Classes). It is recommended to host frontend artifacts in Static Content Servlet like nginx
wrong.

WaveMaker app consists of

not 
is consists of

2020-12-04 05:14 UTC, prasanth-reddy-wavemaker-com commented on learn/app-development/deployment/building-with-maven.md
> +- WaveMaker app is consists of frontend artifacts (HTML, CSS, JS, images, etc), and backend artifacts (Java Classes). It is recommended to host frontend artifacts in Static Content Servlet like nginx
Also 

static content server like nginx

not 

static content **servlet** like nginx

2020-12-04 05:14 UTC, prasanth-reddy-wavemaker-com commented on learn/on-premise/aws/install-prerequisites.md
> +- For upgrade and install the latest version of Docker
To upgrade 

not

**For** upgrade

2020-12-04 05:14 UTC, prasanth-reddy-wavemaker-com commented on learn/on-premise/aws/install-prerequisites.md
> +  - Run the following command for list available versions
Run the following command to list available versions

2020-12-04 05:14 UTC, prasanth-reddy-wavemaker-com commented on learn/on-premise/aws/install-prerequisites.md
> +- If given ssh user has privileges(root/sudo) or user don't have privileges to install/upgrade. WME Installer will automatically install the Docker software. Internet is not required for Installation
wrong sentence. please rewrite this

SSH user performing the install or upgrade needs root/sudo privileges.

2020-12-04 05:14 UTC, prasanth-reddy-wavemaker-com commented on learn/on-premise/aws/install-prerequisites.md
>  - If the user given to the Platform don't have privileged access, then provide below permission for the user given on StudioWorkspace Instance / AppDeployment Instance.
not **don't have**

should be

doesn't have

2020-12-04 05:14 UTC, prasanth-reddy-wavemaker-com commented on learn/on-premise/aws/install-prerequisites.md
> +- Have to execute these commands from a privileged user.
Have to execute these command as a privileged user. 

not

**from a**

2020-12-04 05:14 UTC, prasanth-reddy-wavemaker-com commented on learn/on-premise/aws/install-prerequisites.md
> +  - Make the user as a owner for the docker systemd process.
Replace with:

Make user the owner of the docker `systemd` process

2020-12-04 05:14 UTC, prasanth-reddy-wavemaker-com commented on learn/on-premise/azure/install-prerequisites.md
> +The given ssh user don't have permission to install software Then install below as per operating system.
doesn't 

not 

don't have

2020-12-04 05:14 UTC, prasanth-reddy-wavemaker-com commented on learn/on-premise/azure/install-prerequisites.md
> +- If given ssh user has privileges(root/sudo) or user don't have privileges to install/upgrade. WME Installer will automatically install the Docker software. Internet is not required for Installation
Replace this sentence. It does not have any meaning

2020-12-04 05:14 UTC, prasanth-reddy-wavemaker-com commented on learn/on-premise/azure/install-prerequisites.md
> +- Have to execute these commands from a privileged user.
Have to execute these commands as a 
not 
**from** a

2020-12-04 05:14 UTC, prasanth-reddy-wavemaker-com commented on learn/on-premise/azure/install-prerequisites.md
> +  - Make the user as a owner for the docker systemd process.
Same review comment as above

2020-12-04 05:14 UTC, prasanth-reddy-wavemaker-com commented on learn/on-premise/gcp/install-prerequisites.md
> +- If given ssh user has privileges(root/sudo) or user don't have privileges to install/upgrade. WME Installer will automatically install the Docker software. Internet is not required for Installation
why is there so much duplication of content in these pages?

this sentence occurs in many pages and is wrong in all the places.

2020-12-04 05:14 UTC, prasanth-reddy-wavemaker-com commented on learn/on-premise/gcp/install-prerequisites.md
> +- Have to execute these commands from a privileged user.
More duplication

2020-12-08 06:02 UTC, krishnaraoch commented
@prasanth-reddy-wavemaker-com ,  we made the changes.

2020-12-08 06:03 UTC, krishnaraoch approved these changes

2020-12-08 06:05 UTC, prasanth-reddy-wavemaker-com approved these changes

2020-12-08 06:05 UTC, merged