WaveMaker 10.6 blog
wavemaker/docs pull request #383
Opened 2020-12-09 08:06 UTC by swethakundaram

Draft-1 - do not merge yet.

2020-12-09 08:19 UTC, krishnaraoch requested changes

2020-12-09 08:19 UTC, krishnaraoch commented on website/blog/2020-12-08-wavemaker-release-10-6-version.md
> +Libraries are hosted in the public npm registry (Angular library), and Maven (Jars). Therefore, all the required libraries are available to use without needing to import ZIP files manually.
this line is not relevent to update to date libs

2020-12-09 08:19 UTC, krishnaraoch commented on website/blog/2020-12-08-wavemaker-release-10-6-version.md
> +### External CI-CD for Web and Mobile
You can write this here
Libraries are hosted in the public npm registry (Angular library), and Maven (Jars). Therefore, all the required libraries are available to use without needing to import ZIP files manually.

2020-12-09 12:11 UTC, swethakundaram commented
Added more items to the release notes and pointed them from the blog as pointers to avoid duplicates. Let me know if this is good?

2020-12-09 12:40 UTC, sboyina approved these changes
Mobile related changes are good

2020-12-09 14:54 UTC, krishnaraoch approved these changes

2020-12-10 11:18 UTC, prasanth-reddy-wavemaker-com approved these changes

2020-12-10 11:18 UTC, merged