Spring session blog
wavemaker/docs pull request #397
Opened 2021-01-11 11:42 UTC by swethakundaram

2021-01-11 13:51 UTC, prasanth-reddy-wavemaker-com requested changes
Very well written @swethakundaram 💯

2021-01-11 13:51 UTC, prasanth-reddy-wavemaker-com commented on website/blog/2021-01-04-spring-session-persistence.md
> +You have developed an exceptional application, and the demand for your application is increasing. You need to expand its accessibility and develop a plan to scale your application. Understanding how
we need to add low-code angle to this intro. i will add this statement.

2021-01-11 13:51 UTC, prasanth-reddy-wavemaker-com commented on website/blog/2021-01-04-spring-session-persistence.md
> +title: "Understanding Scaling in WaveMaker Applications"
replace "in" with "of" Scaling of not Scaling in

2021-01-11 13:51 UTC, prasanth-reddy-wavemaker-com commented on website/blog/2021-01-04-spring-session-persistence.md
> +2. Is the application's current growth experiencing [spikes](https://www.guru99.com/spike-testing.html) that lead to service degradation?
Need to change the link to guru99 site or remove it completely.

2021-01-11 13:51 UTC, prasanth-reddy-wavemaker-com commented on website/blog/2021-01-04-spring-session-persistence.md
> +Spring Session manages user-session information while supporting clustered sessions without being tied to an application container specific solution.
manages `user's http session `

2021-01-12 03:48 UTC, prasanth-reddy-wavemaker-com approved these changes

2021-01-12 06:26 UTC, RameshVarmaKothapalli approved these changes

2021-01-12 06:46 UTC, prasanth-reddy-wavemaker-com approved these changes

2021-01-12 06:47 UTC, merged