release notes draft
wavemaker/docs pull request #413
Opened 2021-02-17 12:18 UTC by swethakundaram

Release notes 10.6.4
Update release page
Update known issues

2021-02-17 12:19 UTC, swethakundaram commented
Please take a look at the known issues that should be marked as fixed, @neha2024.

2021-02-18 07:06 UTC, prasanth-reddy-wavemaker-com requested changes
@aparnasj add the fixes regarding angular material form layout issues that went into this build

2021-02-18 07:21 UTC, aparnasj commented
> @aparnasj add the fixes regarding angular material form layout issues that went into this build

@prasanth-reddy-wavemaker-com In 6.4 we didn't make any changes related to angular material form layouts.

2021-02-18 07:23 UTC, prasanth-reddy-wavemaker-com approved these changes

2021-02-18 07:23 UTC, merged