Documented the code editor functionality for the theme builder tool
wavemaker/docs pull request #440
Opened 2021-04-20 11:24 UTC by lovin26

Added a new blog on the code editing feature for themes. Also mentioned the how-to steps and tips for coding.

2021-04-20 13:31 UTC, prasanth-reddy-wavemaker-com approved these changes

2021-04-20 13:32 UTC, prasanth-reddy-wavemaker-com requested changes
Can we mention what users need to know to be able to edit? Is it SAAS/LESS or basic css? @lovin26

2021-04-20 14:03 UTC, lovin26 commented
> Can we mention what users need to know to be able to edit? Is it SAAS/LESS or basic css? @lovin26

Mentioned as editor tips ![image](https://user-images.githubusercontent.com/7323520/115409215-2d1cbf80-a20f-11eb-9e03-030a08728274.png)

2021-05-10 10:43 UTC, prasanth-reddy-wavemaker-com approved these changes

2021-05-10 10:43 UTC, merged