Documentation for Allowed Hosts and Max concurrent-sessions
wavemaker/docs pull request #481
Opened 2021-06-28 06:52 UTC by akshay189

Documentation for handling HostHeader injection and Max Concurrent Sessions in WaveMaker

2021-06-28 07:08 UTC, prasanth-reddy-wavemaker-com requested changes

2021-06-28 07:08 UTC, prasanth-reddy-wavemaker-com commented on learn/app-development/app-security/hostheader-injection.md
> +Host header attacks can lead to
Link to OWASP explanation of this

2021-06-28 07:08 UTC, prasanth-reddy-wavemaker-com commented on learn/app-development/app-security/hostheader-injection.md
> +Handling host header in an unsafe way leads to Host header attacks, here an attacker injects a harmful payload in to host header, Which can manipulate
Start by explaining how WM continuously invests in security.

2021-07-12 06:56 UTC, swethakundaram commented on learn/app-development/app-security/hostheader-injection.md
> +Host header attacks can lead to
done

2021-07-12 13:13 UTC, prasanth-reddy-wavemaker-com approved these changes

2021-07-12 13:13 UTC, merged