Added mtls blog and how-tos doc
wavemaker/docs pull request #631
Opened 2022-08-23 14:27 UTC by praveen-0708

2022-08-24 02:09 UTC, prasanth-reddy-wavemaker-com commented on website/blog/2022-08-23-Support-for-mutual-tls-in-rest-apis.md
> +WaveMaker supports importing REST API as a service which can be used to bind it to a widget in the UI. When the REST API is hit in the design time or runtime, a SSL connection is established between
We should mention that this is needed or works only when you proxy the imported REST API or are creating API orchestration on top of imported API

2022-08-24 02:12 UTC, prasanth-reddy-wavemaker-com requested changes
In mtls blog we should mention about proxy, api orchestration and mtls is not needed if the browser is directly making calls to imported API

2022-08-25 06:18 UTC, prasanth-reddy-wavemaker-com approved these changes

2022-08-25 06:42 UTC, swethakundaram commented
Looks good. Just the mutual-tls.png needs to be designed.

2022-08-26 14:27 UTC, merged