Dsl pagination document
wavemaker/docs pull request #658
Opened 2022-10-19 11:11 UTC by swethakundaram

2022-11-01 05:12 UTC, prasanth-reddy-wavemaker-com requested changes

2022-11-01 05:12 UTC, prasanth-reddy-wavemaker-com commented on learn/how-tos/integrating-server-side-pagination.md
> +title: "Integrating Pagination for Imported APIs"
change title Adding UI Pagination for APIs with server side pagination

2022-11-01 05:12 UTC, prasanth-reddy-wavemaker-com commented on learn/how-tos/integrating-server-side-pagination.md
> +sidebar_label: "Pagination for Imported APIs"
Match the title changes here

2022-11-01 05:12 UTC, prasanth-reddy-wavemaker-com commented on learn/how-tos/integrating-server-side-pagination.md
> +Pagination is a process that separates data into sets. Server-side pagination controls how these sets are retrieved from the database. It is useful when your application does not want to display All
instead of "process" say "a way to represent data in sets of pages".

2022-11-01 05:12 UTC, prasanth-reddy-wavemaker-com commented on learn/how-tos/integrating-server-side-pagination.md
> +Pagination is a process that separates data into sets. Server-side pagination controls how these sets are retrieved from the database. It is useful when your application does not want to display All
The sentence starting with "Instead" needs revisiting. Needs to simplified.

2022-11-01 05:12 UTC, prasanth-reddy-wavemaker-com commented on learn/how-tos/integrating-server-side-pagination.md
> +In WaveMaker, you can achieve Server-side pagination using the DSL (Domain Specific Language) method to the imported APIs, which works seamlessly with the data widgets.
Server side pagination is on the API. So this sentence should be matching the title 

In WaveMaker adding UI pagination for representing APIs that support server side pagination is possible using a little bit of JavaScript API exposed on the widgets such as List, Table.

2022-11-01 05:12 UTC, prasanth-reddy-wavemaker-com commented on learn/how-tos/integrating-server-side-pagination.md
> +Cursor works by returning a pointer to a specific item in the set of data. On subsequent requests, the database returns results after the given pointer.
use the word API instead of database

2022-11-01 05:12 UTC, prasanth-reddy-wavemaker-com commented on learn/how-tos/integrating-server-side-pagination.md
> +**hasMoreItems**: '$header."X-WM-pagination".hasMoreRecords == Y'
This seem to have abruptly ended. May be prefix with.

Pagination controls can be sent both as body of a HTTP Request or a HTTP Header. Here we show how to send these in a HTTP header.

2022-11-01 05:12 UTC, prasanth-reddy-wavemaker-com commented on website/sidebars.json
> +            "how-tos/integrating-server-side-pagination",
match sidebar change as requested above

2022-11-11 11:49 UTC, aparnasj approved these changes

2022-11-11 11:59 UTC, swethakundaram commented
@prasanth-reddy-wavemaker-com, updated the document with the changes you requested. Is the document okay now?

2023-01-19 15:44 UTC, prasanth-reddy-wavemaker-com approved these changes

2023-01-19 15:45 UTC, prasanth-reddy-wavemaker-com approved these changes

2023-01-19 15:45 UTC, merged