Added Manual build process React-native
wavemaker/docs pull request #709
Opened 2023-02-27 11:21 UTC by RitupL

2023-02-27 11:42 UTC, prasanth-reddy-wavemaker-com requested changes
IF this is going to be a small paragraph, just add to existing page here https://docs.wavemaker.com/learn/react-native/build-installers instead of creating a new one.

2023-03-24 08:36 UTC, prasanth-reddy-wavemaker-com commented on learn/react-native/mobile-build-manual.md
> +In application development process, you create iOS Package App Store (IPA) or Android Package Kit (APK) files for developing any mobile application. IPA file is the compressed version of the required
After the mobile app is developed, creating ios... and android... is necessary for deploying it on the app store.

2023-03-24 08:37 UTC, prasanth-reddy-wavemaker-com commented on learn/react-native/mobile-build-manual.md
> +With React Native CLI, a built-in feature, you can create and manage your project on local platforms. You can build apk or ipa on your system from a react-native zip. To help the WaveMaker developers
With React Native CLI, you can build the apk or ipa on your CI/CD machines easily.

2023-05-16 14:31 UTC, swethakundaram approved these changes

2023-06-19 08:31 UTC, closed without merging