Release 11.3
wavemaker/docs pull request #718
Opened 2023-03-16 07:52 UTC by swethakundaram

2023-04-14 06:46 UTC, swethakundaram commented on learn/teams/code-repository.md
> +![Set Repository Default](/learn/assets/wm_coderep_5_f.png)
If you are replacing the image, please the same image name and remove the old image.

2023-04-14 06:57 UTC, prasanth-reddy-wavemaker-com requested changes

2023-04-14 06:57 UTC, prasanth-reddy-wavemaker-com commented on learn/app-development/widgets/prefab/enterprise-marketplace.md
> +:::note
We should define the roles involvled in this activity clearly before using them in sentence.

2023-04-14 06:57 UTC, prasanth-reddy-wavemaker-com commented on learn/app-development/widgets/prefab/enterprise-marketplace.md
> +Any team that has been given access by the super admin can publish the artifacts to Enterprise Marketplace where super admin has complete access over platform.
We should not use the term super admin.

2023-04-14 06:57 UTC, prasanth-reddy-wavemaker-com commented on learn/app-development/widgets/prefab/enterprise-marketplace.md
> +You can only publish an artifact using semantic versioning to mention the version of the artifact.
Rewrite

2023-04-14 06:57 UTC, prasanth-reddy-wavemaker-com commented on learn/app-development/widgets/prefab/enterprise-marketplace.md
> +Semantic versioning is the standard three digit versioning system to publish an artifact that includes, Major.Minor.Patch details of respective artifact. Every project branch can have its own sequenc
Rewrite

2023-04-14 06:57 UTC, prasanth-reddy-wavemaker-com commented on learn/on-premise/configure/config-users-auth-providers.md
> +You can restrict the users from logging into WaveMaker studio by enabling Restrict Login for all users option. Once enabled, all active users get logged out of the platform within three minutes. Only
WE should explain why this was introduced

2023-04-14 06:57 UTC, prasanth-reddy-wavemaker-com commented on learn/on-premise/configure/config-users-auth-providers.md
> +You can restrict the users from logging into WaveMaker studio by enabling Restrict Login for all users option. Once enabled, all active users get logged out of the platform within three minutes. Only
Super admin should not be used.

2023-04-14 06:57 UTC, prasanth-reddy-wavemaker-com commented on learn/teams/code-repository.md
> +When Developer Credentials is selected as Access type for the Code Repository, authentication credentials are required to perform any VCS operation. If you do not have the credentials or expired the
Remove authentication just say credentials

2023-04-14 06:57 UTC, prasanth-reddy-wavemaker-com commented on learn/teams/code-repository.md
> +This field is to enable deletion of a repository from VCS when deleting the project from WaveMaker Studio. Third party users can disable this option and store the project details over VCS without any
Just say "Enables deletion...' no need to start with This field is to enable.

2023-04-14 06:57 UTC, prasanth-reddy-wavemaker-com commented on learn/teams/code-repository.md
> +In this field you add the branch name that is to be added as default branch while creating repository. With this, you can avoid setting the master branch as default and add desired branch as default.
Rewrite.

Want to choose a branch other than master as the branch WaveMaker will push code to? Then just mention that branch name here.

2023-04-14 06:57 UTC, prasanth-reddy-wavemaker-com commented on learn/teams/manage-projects.md
> +You can import a project available on Version Control Systems (VCS) like GitHub, GitLab, Bitbucket and Azure. It also imports commit history and specified branches of the project.
Rewrite

It also imports should be replaced with. Commit history of the specified branch carries over when imported.

2023-04-19 08:25 UTC, swethakundaram-wm approved these changes

2023-04-19 08:26 UTC, prasanth-reddy-wavemaker-com approved these changes

2023-04-24 06:17 UTC, merged