Release notes_11.2.5
wavemaker/docs pull request #721
Opened 2023-03-21 06:44 UTC by RitupL

2023-03-27 09:53 UTC, swethakundaram requested changes

2023-03-27 09:53 UTC, swethakundaram commented on learn/wavemaker-release-notes/v11-2-5.md
> +- Added setAuthorities method in WMAuthentication class to update or set the authorities.
This should be linking to the doc: 
https://docs.wavemaker.com/learn/how-tos/customizing-post-authentication-handlers#wmauthentication-class

And add more info about the method where appropriate

2023-03-27 09:56 UTC, swethakundaram commented on learn/wavemaker-release-notes/v11-2-5.md
> +- Fixed accessibility issues in data table, list, form, switch, tab, radio button, pop-over, carousel, calendar, date, checkbox, label and Nav bar widgets.
@bhargavigundaa, can you help provide some details about what accessibility issues were fixed, maybe one example would help (if we can specify).

2023-03-28 06:31 UTC, krishnaraoch approved these changes
Drop down should show 11.2.5 and 10.14 now.

2023-03-28 18:48 UTC, swethakundaram approved these changes

2023-03-28 18:48 UTC, merged