release 11.3.6
wavemaker/docs pull request #776
Opened 2023-07-25 06:14 UTC by RitupL

2023-07-31 12:45 UTC, bhargavigundaa approved these changes
Good to go

2023-07-31 14:28 UTC, udaysa approved these changes

2023-08-01 09:07 UTC, prasanth-reddy-wavemaker-com commented on learn/wavemaker-release-notes/v11-3-6.md
> +### ADA Issues
Can we use "Accessibility" instead of ADA acronym

2023-08-01 09:09 UTC, prasanth-reddy-wavemaker-com requested changes
Instead of ADA use the word "Accessibility"

2023-08-01 11:39 UTC, sboyina approved these changes

2023-08-01 14:51 UTC, merged