added sentry doc
wavemaker/docs pull request #792
Opened 2023-08-28 09:27 UTC by shilwantkumar

2023-08-28 10:02 UTC, prasanth-reddy-wavemaker-com commented
This looks to include crashlytics doc also. May be we can close #791 ?
@shilwantkumar

2023-08-28 10:05 UTC, prasanth-reddy-wavemaker-com requested changes

2023-08-28 10:05 UTC, prasanth-reddy-wavemaker-com commented on learn/react-native/integrating-sentry.md
> +- Sentry treats React Native as a first-class citizen and we have collaborated with Sentry to make sure Expo is, too.
"we have collaborated" -- how?

2023-08-28 10:05 UTC, prasanth-reddy-wavemaker-com commented on learn/react-native/integrating-sentry.md
> +- We trust it for our projects at Expo.
? Copy-Pasted, but does not make sense here.

2023-08-28 10:05 UTC, prasanth-reddy-wavemaker-com commented on learn/react-native/integrating-sentry.md
> +[Sign up for Sentry](https://sentry.io/signup/) (it's free), and create a project in your Dashboard. Take note of your organization slug, project name, and DSN as you'll need them later:
You can just link to Sentry documentation instead of including instructions from that site here.

2023-08-28 10:05 UTC, prasanth-reddy-wavemaker-com commented on learn/react-native/integrating-sentry.md
> +### 2. Installation
This should be step 1

2023-08-28 10:05 UTC, prasanth-reddy-wavemaker-com commented on learn/react-native/integrating-sentry.md
> +Here, we created two buttons, one for the test log and another for crashing the app manually.
Same comments as i have previously made on Crashlytics also apply here.

2023-08-28 11:31 UTC, shilwantkumar commented on learn/react-native/integrating-sentry.md
> +- Sentry treats React Native as a first-class citizen and we have collaborated with Sentry to make sure Expo is, too.
I am not completed yet

2023-09-27 09:37 UTC, prasanth-reddy-wavemaker-com approved these changes

2023-09-27 09:38 UTC, merged