Blog on Design Tokens
wavemaker/docs pull request #836
Opened 2023-10-20 06:26 UTC by lovin26

Introduced a new blog on Design Tokens

2023-10-25 05:28 UTC, prasanth-reddy-wavemaker-com requested changes

2023-10-25 05:28 UTC, prasanth-reddy-wavemaker-com commented on website/blog/2023-10-18-Design-Tokens.md
> +There is a lot of talk going on lately about design tokens. So, what are design tokens? As I understand it, design tokens are platform-agnostic variables that represent the look and feel of your prod
Remove the first sentence.

2023-10-25 05:28 UTC, prasanth-reddy-wavemaker-com commented on website/blog/2023-10-18-Design-Tokens.md
> +**“Who is going to use it and how?”**
Change to H3 instead use '###'.

2023-10-25 05:28 UTC, prasanth-reddy-wavemaker-com commented on website/blog/2023-10-18-Design-Tokens.md
> +In the next blog post, see how it works with SaaS applications.
see how it works iwth Saas application and with WaveMaker.

2023-10-25 21:47 UTC, lovin26 commented
It looks good to me

2023-10-26 05:22 UTC, prasanth-reddy-wavemaker-com approved these changes

2023-10-26 05:22 UTC, merged