Push notification
wavemaker/docs pull request #846
Opened 2023-11-24 08:48 UTC by shilwantkumar

2023-11-24 08:54 UTC, prasanth-reddy-wavemaker-com approved these changes

2023-11-24 09:12 UTC, prasanth-reddy-wavemaker-com requested changes
IT is not clear to me after reading this write up how i can connect a UI component to a message that has been pushed to me.
Can we have a model variable that the incoming message is added to and bind UI widget to it? 

Also the sample code has some log statements that should be removed.

@shilwantkumar

2023-12-13 04:54 UTC, prasanth-reddy-wavemaker-com reviewed
Why does the code need Page.refresh() ?@shilwant

2023-12-14 06:31 UTC, shilwantkumar commented
For component re-rendering we are using Page.refresh();

2023-12-18 10:51 UTC, prasanth-reddy-wavemaker-com approved these changes

2023-12-18 10:51 UTC, merged