added release notes 11.5.2
wavemaker/docs pull request #860
Opened 2023-12-19 10:45 UTC by RitupL

2023-12-19 11:03 UTC, sboyina approved these changes

2023-12-19 11:08 UTC, krishnaraoch requested changes

2023-12-19 11:08 UTC, krishnaraoch commented on learn/wavemaker-release-notes/v11-5-2.md
> +- Fixed cookie Samsite property issue that was not getting honored for CSRF token.
Same Site

2023-12-20 04:52 UTC, krishnaraoch approved these changes

2023-12-20 11:41 UTC, swethakundaram approved these changes

2023-12-20 11:42 UTC, merged