added cordova deprecation blog
wavemaker/docs pull request #876
Opened 2024-03-04 10:28 UTC by RitupL

2024-03-05 08:02 UTC, prasanth-reddy-wavemaker-com approved these changes

2024-03-05 08:39 UTC, neha2024 requested changes

2024-03-05 08:39 UTC, neha2024 commented on website/blog/2024-02-29-Deprecation-notice-for-cordova-project-type.md
> +For us to serve our customers better, we are moving our mobile focus to React Native only. With the release of 11.6.0, we will start providing minimal support to Cordova projects.
considering the benefits/advantages react native provides, we are moving our mobile focus to React native only to serve our customers better.

2024-03-05 08:39 UTC, neha2024 commented on website/blog/2024-02-29-Deprecation-notice-for-cordova-project-type.md
> +For us to serve our customers better, we are moving our mobile focus to React Native only. With the release of 11.6.0, we will start providing minimal support to Cordova projects.
we are going to discontinue support for creating new cordova projects.

2024-03-12 04:40 UTC, prasanth-reddy-wavemaker-com approved these changes

2024-03-12 07:28 UTC, neha2024 approved these changes
looks good to me

2024-03-12 07:30 UTC, merged