updated skeleton loader doc
wavemaker/docs pull request #947
Opened 2024-08-20 06:10 UTC by RitupL

2024-08-23 09:18 UTC, swethakundaram requested changes

2024-08-23 09:18 UTC, swethakundaram commented on learn/react-native/app-loader.md
> +- Page level
point to the section where it applies for page, widget, and class headers.

2024-08-23 09:18 UTC, swethakundaram commented on learn/react-native/app-loader.md
> +Skeleton Loader gets applied across the application only if a service variable is available for the application and the Spinner Context is also set as Page.
point to service variable documentation and spinner context documentation.

2024-08-23 09:18 UTC, swethakundaram commented on learn/react-native/app-loader.md
> +1. skeleton: It is the outer container of the Skeleton component.
Use apt formatting, such as code blocks for classes in this case. And use a header for this section.

2024-08-23 09:18 UTC, swethakundaram commented on learn/react-native/app-loader.md
> +Container type widgets are recently getting supported by Skeleton Loader. This category includes the below widgets,
remove the word recently and add a better explanation for this.

2024-08-23 09:18 UTC, swethakundaram commented on learn/react-native/app-loader.md
> +The widgets in this category have child widgets on which the Skeleton Loader is not applied by default. To apply it on the child widgets within the Container type widget, set **`showskeletonchildren`
please include the code snippet of the usage.

2024-08-23 09:18 UTC, swethakundaram commented on learn/react-native/app-loader.md
> +#### Customization using Lottie Animation
Need code snippet and instructions to apply clearly. Use images and video in this case.

2024-08-23 09:18 UTC, swethakundaram commented on learn/react-native/app-loader.md
> +It is required to use Lottie widget in the application to implement the above.
point to Lottie widget documentation

2024-11-19 12:43 UTC, swethakundaram-wm approved these changes

2024-11-19 12:43 UTC, swethakundaram approved these changes

2024-11-19 12:43 UTC, merged